### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Ademord** [keijiro/TinyYOLOv2Barracuda#10]
Hello, I am trying out your project and I have some questions:
- Why are the classes limited to the ones in Config.cs? I think the original model has more (?).
- Why doesn't the VisualizerGPU show any labels during detection like the VisualizerCPU?
- I am trying to understand what the pipeline is (reverse engineering the code), and the differences between the two Visualizers are a bit confusing, any help would be appreciated.

**Comment by keijiro** [comment]
> Why are the classes limited to the ones in Config.cs? I think the original model has more (?).

The "Tiny" model I used in the project only recognizes them.

> Why doesn't the VisualizerGPU show any labels during detection like the VisualizerCPU?

It's not easy to render text without help of CPU. I don't want to introduce extra complexity to this small sample project.

> I am trying to understand what the pipeline is (reverse engineering the code), and the differences between the two Visualizers are a bit confusing, any help would be appreciated.

I'd recommend using the CPU approach. The "GPU-only method" is just for extreme game developers who don't have luxury to use CPU-side resources.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
