### ISSUE TITLE
yolov3 or v4 integration?

### ISSUE THREAD

**Issue by Ademord** [keijiro/TinyYOLOv2Barracuda#11]
i tried to use a yolov3 as i describe in [this ](https://github.com/Unity-Technologies/barracuda-release/issues/119#issuecomment-858649366)post, but i was wondering if you could tell me if i am doing something wrong or do you have a version with better results than the one this repo has (either more classes or better performance?, or do you think it is a problem of my environment, not realistic enough?)

**Comment by keijiro** [comment]
I have never tried YOLOv3 or YOLOv4, but my understanding is that they need different preprocess/postprocess, so I think you have to rewrite most part of C#/compute shader code. In other words, this project is totally useless to run those models.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
