### ISSUE TITLE
Can I train this on custom classes?

### ISSUE THREAD

**Issue by pallavimohansaab** [keijiro/TinyYOLOv2Barracuda#12]
Hi,

I've been searching everywhere but I can't find a way to train TinyYolov2 to detect 3 custom object classes. Any pointers would be great.

Alternatively, is there any way to train a model to detect 3 objects in a frame and have that model work with Barracuda? I see that only certain architectures are supported and TinyYOLOv2 seems to be the most suitable of the lot.

Thanks in advance!

**Comment by keijiro** [comment]
Honestly saying, I have no idea! I don't have any experience about ML model training -- I only have knowledge and experience on ML model inference.

So, please educate yourself. There are tons of tutorials/textbooks about machine learning.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
