### ISSUE TITLE
Shader error in 'Hidden/TinyYOLOv2/Visualizer': Couldn't open include file '../Common.hlsl'. at line 6

### ISSUE THREAD

**Issue by michalek-marcin** [keijiro/TinyYOLOv2Barracuda#3]
Hi,

If i try to edit Common.hlsl file to change anchors and classes count for my custom model, then Visualizer and Pixelizer shaders crashes with error:
`Shader error in 'Hidden/TinyYOLOv2/Visualizer': Couldn't open include file '../Common.hlsl'. at line 6`

I tried to edit Common.hlsl file with Visual Studio, Atom and Notepad. Always when I save Common.hlsl file, shaders crashes.
I also tried to reimport shaders, but without success.

Can somebody tell me how can I edit this file?

**Comment by keijiro** [comment]
Did you modify this line?

https://github.com/keijiro/TinyYOLOv2Barracuda/blob/main/Assets/Test/Visualizer.shader#L6

This should be `"../Shader/Common.hlsl"`, but your error message says `../Common.hlsl`.

**Comment by michalek-marcin** [comment]
Yes I did. Error code which I wrote previously I got when I tried to put Common.hlsl file to Assets folder (when file was in Shader folder I also had problems).
I found workaround -> I put all the files: `Common, Preprocess, Postprocess1 and Postprocess2` in `Assets/Resources/Shaders` folder:
![image](https://user-images.githubusercontent.com/54703654/109173479-2aa86700-7784-11eb-9f36-1f67e8b1a18e.png)

You can reproduce this by just edit and save `Common.hlsl` file. Unity for some reason can't reimport Shaders when you change file which is included using directive: `#include "Common.hlsl"`.

Unity version: 2020.2.4

**Comment by michalek-marcin** [comment]
I have another problem. I was struggling with the conversion from darknet to ONNX for several days, but today I finally succeed.

I have two versions of yolov2-tiny: voc (20 classes) and coco (80 classes) converted by me.
VOC model works out of the box, but COCO doesn't. 
I changed:
- `ClassCount` and `_labels` in Config file
- `CLASS_COUNT `and `anchors `in Common.hlsl
- model assigned to TinyYOLOv2 asset.

Here is my COCO model:
https://drive.google.com/file/d/1epFgd3Sx0NikGB-Y9oHsVWlACxclmjnL/view?usp=sharing

Could you try to check my model and tell me what else do I need to change?

**Comment by keijiro** [comment]
Could you create a new issue for a topic that is not related to the original post?

I'd like to close this issue if the problem in the original post was solved.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
