### ISSUE TITLE
Using video file instead of WebCam?

### ISSUE THREAD

**Issue by shampliu** [keijiro/TinyYOLOv2Barracuda#5]
Hi there, 

This is my first time using Unity. I got the project to run but I was wondering how to input a video file to the Pixelizer scene instead of the WebCamTexture? I notice in the README, the example seems to use a video recorded on a camera and not a webcam.

**Comment by keijiro** [comment]
I just used a UVC-compatible HDMI capture device (that works as a webcam for PC) for those examples.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
