### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by michalek-marcin** [keijiro/TinyYOLOv2Barracuda#6]
Hi,

I already have full screen preview with working image recognition in landscape mode, but I need portrait mode (probably portrait mode only without autorotation feature) in iOS app. I think I must rotate texture before execute ProcessImage function in ObjectDetector or maybe in Preprocess ComputeShader. But I don't know how. Has anyone managed to do it?

**Comment by keijiro** [comment]
Unfortunately, I can't consult your project here. Please understand that this issue tracker is for tracking problems with the specific project (TinyYOLOv2Barracuda). You can use the Unity forum to solve generic issues like this one.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
