### ISSUE TITLE
Using a headset instead of webcam

### ISSUE THREAD

**Issue by romitgodi** [keijiro/TinyYOLOv2Barracuda#7]
Hello Keijiro!

This is not an issue with the project but with using a different source instead of a webcam.
I am using a mixed reality headset whose cameras are not accessible as web cameras. Therefore I can't use WebCamTexture, although the headset shows up in the list when I print the devices log. Have you tried with a different video source? Do you know an alternative to WebCamTexture?

Thanks!

**Comment by keijiro** [comment]
The `WebCamTexture` class is derived from the `Texture` class, so you can easily modify it to support other texture classes.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
