### ISSUE TITLE
Can I ask if this can be implemented on MRTK-WEBRTC?

### ISSUE THREAD

**Issue by Kabster17** [keijiro/TinyYOLOv2Barracuda#8]
Hi there, 

I have noticed if you have done great works with Barracuda in Unity and I would like to ask you if you have done any implementation with mrtk-webrtc and barracuda?
Right now, I am looking to run Barracuda-YOLO inference engine on MRTK-Webrtc stream from HoloLens and would like to know if its possible? 
I am new to Unity and its development and would really appreciate your help. 
Thanks.

**Comment by keijiro** [comment]
No. Actually, I have no idea about what MRTK-WEBRTC is.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems on this project.
