### ISSUE TITLE
How should I convert darknet model to onnx format?

### ISSUE THREAD

**Issue by apex20** [keijiro/TinyYOLOv2Barracuda#9]
Hi, I'm kinda struggling with how to use my custom model.

I'm testing with tiny YOLO v2(voc) files(.cfg, .weights) before I convert my custom weight.

First, I converted Darknet(yolov2-tiny-voc.cfg and yolov2-tiny-voc.weights) to TF model(.pb).

What I found out is that I have to freeze the TF graph so I did. Then I converted it to ONNX model.

I used DW2TF for conversion.
https://github.com/jinyu121/DW2TF

Could you help me how to get it work?

Here's the model that I used.
https://kookmin-my.sharepoint.com/:u:/g/personal/apex_kookmin_kr/EeoCfr_a6KlLitYRePduwVoBn1krOowxFsF4JVIkldGwAQ

**Comment by keijiro** [comment]
Please understand that this issue tracker is dedicated for solving problems happened in this specific project -- not a place for providing free consulting for random projects.

Unfortunately, I have no idea about converting Darknet models into ONNX. According to the ONNX model zoo (where I obtained the ONNX file used in this project), it's converted from Darknet -> Core ML -> ONNX. I think you can get some idea from articles linked from the page.

https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems relevant to this project.
